# 1. laboratorijska vježba iz Numeričke matematike

Ime i prezime: Mihael Miličević

1 . Napišite primjer jedne računske operacije koju ste izvršili u računalu, a da pri tome ne dobijete vrijednost koja se dobije egzaktno, računajući na papiru

In [137]:
x = 2**64 * 1.0
y = 1E-9
z = x+y

print(f'Za z-x očekujemo kao rezultat {y}, a dobijemo {z-x}')

Za z-x očekujemo kao rezultat 1e-09, a dobijemo 0.0


   2 . Napišite primjer računske operacije koja u računalu daje izlaz *inf* i operacije koja kao izlaz daje *nan*

In [138]:
import numpy as np
olderr = np.seterr(all='ignore') 

print(f'Primjer za inf -> np.exp(1000) = {np.exp(1000)}')
print(f"Primjer za nan -> float(Inf) - float(Inf) = {float('Inf') - float('Inf')}")

Primjer za inf -> np.exp(1000) = inf
Primjer za nan -> float(Inf) - float(Inf) = nan


3 a). U računalu rješavamo kvadratnu jednadžbu.
  $$(x-10^{10})(x-10^{-10})=0$$
  odnosno jednadžbu 
  $$x^2+(-10^{10}-10^{-10})x+1=0$$
  Odredite rješenja koristeći formulu 
  $$x_{1/2}=\frac{-b\pm\sqrt{b^2-4ac}}{2a}$$
 

In [139]:
import numpy as np
from math import sqrt

a = 1.0
c = 1.0
b = -1.e+10-1.e-10

D = sqrt(b**2 - 4 * a * c)

x1 = (-1 * b) + D
x1 = x1 / 2 * a

x2 = (-1 * b) - D
x2 = x2 / 2 * a

print(f'x1 = {x1}, x2 = {x2}')

x1 = 10000000000.0, x2 = 0.0


3 b) Razlikuju li se rješenja od onih koje računamo na papiru? Kako možemo poboljšati računanje rješenja (osim da koristimo naredbu roots)?

Rješenja koja se dobiju se razlikuju od rješenja koja bismo dobili računanjem na papiru. Rješenje možemo poboljšati korištenjem Vieteovih formula.

In [140]:
import numpy as np

a = 1.0
c = 1.0
b = -1.e+10-1.e-10

D = sqrt(b**2 - 4 * a * c)

x1 = (-1 * b) + D
x1 = x1 / 2 * a

x2 = (-1 * b) - D
x2 = x2 / 2 * a

prvi = x1 if abs(x1) > abs(x2) else x2
drugi = c / (prvi * a)

print(f'x1 = {prvi}, x2 = {drugi}')

x1 = 10000000000.0, x2 = 1e-10


4 . Prepostavimo da imamo singularan sustav
 $$x+2y=3$$
 $$2x+4y=6$$
 
 Pomnožite drugu jednadžbu s 0.3. te potom riješite sustav koristeći [link](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html).
 Zašto smo dobili samo jedno rješenje, a u realnosti ih ima beskonačno mnogo?

In [141]:
A = np.array([[1.0, 2.0], [0.6, 1.2]])
b = np.array([3.0, 1.8])

print(np.linalg.solve(A,b))


LinAlgError: Singular matrix

% napisati rečenicu objašnjenja


5 a. Odredite $PLU$ dekompoziciju matrice 
$$A=\begin{bmatrix} 2 & 1 & 3 & 4\\ -2 & 1 &-1& -2\\ 4 & 4& 5& 11\\ -2 & 1 & -7 & -1
\end{bmatrix}$$
koristeći biblioteku SciPy, te ispišite matrice $P$ (odnosno $P_1=P^T$), $L$, $U$. tako da je $P_1A=LU.$

In [ ]:
from scipy.linalg import lu
A=np.array([[2.0, 1.0, 3.0, 4.0],[-2.0, 1.0, -1.0, -2.0],[4.0, 4.0, 5.0, 11.0],[-2.0, 1.0, -7.0, -1.0]])

P, L, U = lu(A)
P = np.transpose(P)

print(f'P = \n{P}\n')
print(f'L = \n{L}\n')
print(f'U = \n{U}\n')

P = 
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]

L = 
[[ 1.          0.          0.          0.        ]
 [-0.5         1.          0.          0.        ]
 [-0.5         1.          1.          0.        ]
 [ 0.5        -0.33333333 -0.16666667  1.        ]]

U = 
[[ 4.          4.          5.         11.        ]
 [ 0.          3.          1.5         3.5       ]
 [ 0.          0.         -6.          1.        ]
 [ 0.          0.          0.         -0.16666667]]



5 b.Koristeći već ugrađenu funkciju iz biblioteke scipy za rješavanje trokutastih sustava riješite sustav $Ax=b$ ako je 
$$b=\begin{bmatrix}10\\ -4\\ 24\\-9\end{bmatrix}$$
odnosno riješite
$$Ly=P_1b$$
$$Ux=y$$
Pomoć je 
[ovaj link](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve_triangular.html#scipy.linalg.solve_triangular).

In [ ]:
from scipy.linalg import solve_triangular

b = np.array([10, -4, 24, -9])

print(solve_triangular(A, b))

[ 10.  -1. -15.   9.]


6 . Riješite sustav  $Ax=b$, gdje je $A$ trodijagonalna matrica 
$$A=\begin{bmatrix} 2 & -1 & 0 & 0 & 0\\ -1 & 2 &-1& 0 & 0\\ 0& -1& 2& -1& 0\\ 0 & 0 & -1 & 2 & -1\\
0& 0& 0 &-1& 2
\end{bmatrix}\quad b=\begin{bmatrix} 1 \\ 0\\0\\0\\ 1 \end{bmatrix}$$
koristeći funkciju definiranu [ovaj link](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve_banded.html#scipy.linalg.solve_banded)

In [ ]:
from scipy.linalg import solve_banded
import numpy as np

ab = np.array([[0, -1, -1, -1, -1], [2, 2, 2, 2, 2], [-1, -1, -1, -1, 0]])
b = np.array([1, 0, 0, 0, 1])

print(solve_banded((1,1), ab, b))

[1. 1. 1. 1. 1.]


7.a) Zadana je matrica 
$$A=\begin{bmatrix} 49& 14 & 21\\ 14& 5 & 11\\ 21 & 11 & 43\end{bmatrix}$$
Odredite faktorizaciju Choleskog koristeći funkciju [link](https://numpy.org/doc/stable/reference/generated/numpy.linalg.cholesky.html)

In [ ]:
from scipy.linalg import cholesky, LinAlgError
import numpy as np

A = np.array([[49.0, 14.0, 21.0], [14.0, 5.0, 11.0], [21.0, 11.0, 43.0]])

print(np.transpose(cholesky(A)))

[[7. 0. 0.]
 [2. 1. 0.]
 [3. 5. 3.]]


7b)Zadana je matrica 
$$B=\begin{bmatrix} 49& 14 & 21\\ 14& 5 & 11\\ 21 & 11 & 30\end{bmatrix}$$
Odredite faktorizaciju Choleskog, ako postoji.

In [ ]:
A = np.array([[49.0, 14.0, 21.0], [14.0, 5.0, 11.0], [21.0, 11.0, 30.0]])

try:
    print(np.transpose(cholesky(A)))
except LinAlgError:
    print("Matrica nije pozitivno definitna i stoga nema faktorizaciju Choleskog!")

Matrica nije pozitivno definitna i stoga nema faktorizaciju Choleskog!


8 . Ispiši svojstvene vrijednosti za matricu iz zadatka 7a i 7b. Koja je poveznica  s pozitivnom definitnošću?

In [ ]:
import numpy as np

A = np.array([[49, 14, 21], [14, 5, 11], [21, 11, 43]])
B = np.array([[49, 14, 21], [14, 5, 11], [21, 11, 30]])

print(f'Svojstvene vrijednosti od A: {np.linalg.eigvalsh(A)}')
print(f'Svojstvene vrijednosti od B: {np.linalg.eigvalsh(B)}')

print("Matrica B nema sve svojstvene vrijednosti strogo pozitivne, pa nije pozitivno definitna, pa nema faktorizaciju Choleskog!")

Svojstvene vrijednosti od A: [ 0.24704531 24.81409368 71.93886101]
Svojstvene vrijednosti od B: [-0.17473351 16.59936382 67.57536969]
Matrica B nema sve svojstvene vrijednosti strogo pozitivne, pa nije pozitivno definitna, pa nema faktorizaciju Choleskog!


9 . Zadan je vektor 
$$x=\begin{bmatrix} 1\\ 2\\ 3\\ 4\\ 5\end{bmatrix}$$
Koristeći funkcije [ovaj link](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html) izračunajte normu ovog vektora i to 1-normu, $\infty$-normu i euklidsku normu.

In [ ]:
from scipy.linalg import norm

x = np.array([1, 2, 3, 4, 5])

print(f'1-norma vektora x: {norm(x, ord=1)}')
print(f'inf-norma vektora x: {norm(x, ord=np.inf)}')
print(f'euklidska norma vektora x: {norm(x)}')

1-norma vektora x: 15.0
inf-norma vektora x: 5.0
euklidska norma vektora x: 7.416198487095663


10 .  Zadana je matrica 
$$F=\begin{bmatrix}
5&4&3&2&1\\
4&4&3&2&1\\
0& 3& 3& 2& 1\\
0& 0& 2& 2& 1\\
0& 0& 0&1& 1
\end{bmatrix}$$
Odredite 1- normu ove matrice koristeći [ovaj link](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html) te uvjetovanost ove matrice u 1- normi

In [ ]:
from scipy.linalg import norm, inv

F = np.array([[5,4,3,2,1],[4,4,3,2,1],[0,3,3,2,1],[0,0,2,2,1],[0,0,0,1,1]])
G = inv(F)

f = norm(F, ord=1)
g = norm(G, ord=1)

print(f'1-norma matrice F: {f}')
print(f'1-norma inverza matrice F: {g}')
print(f'uvjetovanost matrice F u 1-normi je umnožak prethodna dva rezultata: {f * g}')

1-norma matrice F: 11.0
1-norma inverza matrice F: 80.99999999999974
uvjetovanost matrice F u 1-normi je umnožak prethodna dva rezultata: 890.9999999999972


11 . Zadana je matrica 
$$\begin{bmatrix} -9000 & 8000 & 8000\\ 7000 & 1& 0\\ 7000 & 0  & 0\end{bmatrix}$$
Probajte pronaći dijagonalnu matricu $D$ tako da matrica $DAD$ ima manju (odnosno bolju) uvjetovanost, te ispišite tu uvjetovanost.

In [ ]:
import numpy as np

A = np.array([[-9000, 8000, 8000], [7000, 1, 0], [7000, 0, 0]])
print(np.linalg.cond(A))

D = np.array([[0.1, 0, 0], [0, 1.1, 0], [0, 0, 1.1]])

DA = np.matmul(D, A)
DAD = np.matmul(DA, D)

print(np.linalg.cond(DAD))

32154.864190318127
2078.2913776847363
